epa:
  preprocess:
    base: /mnt/2TB_WD/rishi/EPA
    years: [2022, 2023, 2024, 2025]
    by_site_dir: /mnt/2TB_WD/rishi/EPA/epa_data_by_site
    output_dir: /home/student/rishi/EPA_sites_separate_pols
    target_start: "2023-01-01"
    target_end:   "2025-12-31 23:00"

  imputation:
    dicts_dir: visualize_epa_dicts
    input_dir: /home/student/rishi/EPA_sites_separate_pols
    output_dir: /home/student/rishi/EPA_sites_imputed
    max_gap_hours: 336
    min_data_pct: 70
    n_neighbors: 5
    max_workers: 4
    date_range:
      start: "2023-01-01"
      end:   "2025-12-31 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"

  visualise:
    folder: /home/student/rishi/EPA_sites_separate_pols
    date_range:
      start: "2023-01-01 00:00:00"
      end:   "2025-12-31 23:00:00"
    output:
      dicts_dir: visualize_epa_dicts
      image_dir:  visualize_epa_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 15
      "PM10 (µg/m³)":  45
      "NO2 (µg/m³)":   25
      "SO2 (µg/m³)":   40
      "CO (mg/m³)":    4
      "Ozone (µg/m³)": 100

cpcb:
  preprocess:
    zip_path:     /home/student/rishi/cpcb_data.zip
    raw_dir:      /home/student/rishi/CPCB/cpcb_raw
    input_folder: /home/student/rishi/CPCB/cpcb_raw/cpcb_data
    output_dir:   /home/student/rishi/CPCB/sites_comb_separate_pols
    max_workers:  24

  imputation:
    dicts_dir: visualize_cpcb_dicts
    input_dir: /home/student/rishi/CPCB/sites_comb_separate_pols
    output_dir: /home/student/rishi/CPCB/sites_imputed
    max_gap_hours: 336
    min_data_pct: 70
    n_neighbors: 5
    max_workers: 4
    date_range:
      start: "2023-01-01"
      end:   "2025-12-31 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"

  visualise:
    folder: /home/student/rishi/CPCB/sites_comb_separate_pols
    date_range:
      start: "2023-01-01 00:00:00"
      end:   "2025-12-31 23:00:00"
    output:
      dicts_dir: visualize_cpcb_dicts
      image_dir:  visualize_cpcb_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 75
      "PM10 (µg/m³)":  150
      "NO2 (µg/m³)":   120
      "SO2 (µg/m³)":   125
      "CO (mg/m³)":    7
      "Ozone (µg/m³)": 160
