epa:
  preprocess:
    zip: false
    zip_path:     /mnt/2TB_WD/rishi/epa_data
    unzip_dir: /mnt/2TB_WD/rishi/epa
    years: [2022, 2023, 2024, 2025]
    by_year_by_site_dir: /mnt/2TB_WD/rishi/epa/epa_data_by_site_by_year
    by_site_all_years_dir: /mnt/2TB_WD/rishi/epa/epa_data_by_site_all_years
    target_start: "2022-07-01 00:00:00"
    target_end:   "2025-06-30 23:00:00"

  visualise:
    make_dicts: false
    folder: /mnt/2TB_WD/rishi/epa/epa_data_by_site_all_years
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    output:
      dicts_dir: visualize_epa_dicts
      image_dir:  visualize_epa_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 15
      "PM10 (µg/m³)":  45
      "NO2 (µg/m³)":   25
      "SO2 (µg/m³)":   40
      "CO (mg/m³)":    4
      "Ozone (µg/m³)": 100
    
  imputation:
    dicts_dir: visualize_epa_dicts
    input_dir: /mnt/2TB_WD/rishi/epa/epa_data_by_site_all_years
    output_dir: /mnt/2TB_WD/rishi/epa/imputed
    max_gap_hours: 336
    max_data_missing: 30
    max_workers: 24
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"

cpcb:
  preprocess:
    zip: false
    zip_path:     /mnt/2TB_WD/rishi/cpcb_data.zip
    unzip_dir:    /mnt/2TB_WD/rishi/cpcb/cpcb_unzipped
    input_folder: /mnt/2TB_WD/rishi/cpcb/cpcb_unzipped/cpcb_data
    output_dir:   /mnt/2TB_WD/rishi/cpcb/separated
    max_workers:  24


  visualise:
    make_dicts: true
    folder: /mnt/2TB_WD/rishi/cpcb/separated
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    output:
      dicts_dir: /mnt/2TB_WD/rishi/cpcb/vis_dicts
      image_dir:  visualize_cpcb_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 75
      "PM10 (µg/m³)":  150
      "NO2 (µg/m³)":   120
      "SO2 (µg/m³)":   125
      "CO (mg/m³)":    7
      "Ozone (µg/m³)": 160

  imputation:
    dicts_dir: /mnt/2TB_WD/rishi/cpcb/vis_dicts
    input_dir: /mnt/2TB_WD/rishi/cpcb/separated
    output_dir: /mnt/2TB_WD/rishi/cpcb/sites_imputed
    max_gap_hours: 336
    max_data_missing: 30
    max_workers: 24
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"

  ttm:
    model_path: "ibm-granite/granite-timeseries-ttm-r2"
    input_dir:  /mnt/2TB_WD/rishi/cpcb/sites_imputed
    output_dir: /mnt/2TB_WD/rishi/cpcb/ttm_results_v1
    context_length:    168
    prediction_length: 12
    batch_size:        64
    seed:              42
    timestamp_column: "Timestamp"
    id_columns: []

  chronos:
    model_path: "amazon/chronos-2"
    input_dir:  /mnt/2TB_WD/rishi/cpcb/sites_imputed
    output_dir: /mnt/2TB_WD/rishi/cpcb/chronos_results_v1
    context_length:    168
    prediction_length: 12
    batch_size:        256
    timestamp_column: "Timestamp"