epa:
  preprocess:
    zip: false
    zip_path:     /mnt/2TB_WD/rishi/epa_data
    unzip_dir: /mnt/2TB_WD/rishi/epa
    years: [2022, 2023, 2024, 2025]
    by_year_by_site_dir: /mnt/2TB_WD/rishi/epa/epa_data_by_site_by_year
    by_site_all_years_dir: /mnt/2TB_WD/rishi/epa/epa_data_by_site_all_years
    target_start: "2022-07-01 00:00:00"
    target_end:   "2025-06-30 23:00:00"

  visualise:
    make_dicts: true
    folder: /mnt/2TB_WD/rishi/epa/epa_data_by_site_all_years
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    output:
      dicts_dir: /mnt/2TB_WD/rishi/epa/visualize_dicts
      image_dir:  visualize_epa_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 15
      "PM10 (µg/m³)":  45
      "NO2 (µg/m³)":   25
      "SO2 (µg/m³)":   40
      "CO (mg/m³)":    4
      "Ozone (µg/m³)": 100
    
  imputation:
    dicts_dir: /mnt/2TB_WD/rishi/epa/visualize_dicts
    input_dir: /mnt/2TB_WD/rishi/epa/epa_data_by_site_all_years
    output_dir: /mnt/2TB_WD/rishi/epa/imputed
    max_gap_hours: 336
    max_data_missing: 30
    max_workers: 24
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"


cpcb:
  preprocess:
    zip: false
    zip_path:     /mnt/2TB_WD/rishi/cpcb_data.zip
    unzip_dir:    /mnt/2TB_WD/rishi/cpcb/cpcb_unzipped
    input_folder: /mnt/2TB_WD/rishi/cpcb/cpcb_unzipped/cpcb_data
    output_dir:   /mnt/2TB_WD/rishi/cpcb/separated
    max_workers:  24


  visualise:
    make_dicts: true
    folder: /mnt/2TB_WD/rishi/cpcb/separated
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    output:
      dicts_dir: /mnt/2TB_WD/rishi/cpcb/vis_dicts
      image_dir:  visualize_cpcb_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 75
      "PM10 (µg/m³)":  150
      "NO2 (µg/m³)":   120
      "SO2 (µg/m³)":   125
      "CO (mg/m³)":    7
      "Ozone (µg/m³)": 160

  imputation:
    dicts_dir: /mnt/2TB_WD/rishi/cpcb/vis_dicts
    input_dir: /mnt/2TB_WD/rishi/cpcb/separated
    output_dir: /mnt/2TB_WD/rishi/cpcb/sites_imputed
    max_gap_hours: 336
    max_data_missing: 30
    max_workers: 24
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"


aurn:
  preprocess:
    zip: false
    zip_path:         /mnt/2TB_WD/rishi/aurn.zip
    unzip_dir:        /mnt/2TB_WD/rishi/aurn
    rdata_conversion: true
    rdata_dir:        /mnt/2TB_WD/rishi/aurn/aurn_data
    csv_dir:          /mnt/2TB_WD/rishi/aurn/aurn_csv
    output_dir:       /mnt/2TB_WD/rishi/aurn/aurn_processed
    date_start:       "2022-07-01 00:00:00"
    date_end:         "2025-06-30 23:00:00"
    max_workers:      24

  visualise:
    make_dicts: true
    folder: /mnt/2TB_WD/rishi/aurn/aurn_processed
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    output:
      dicts_dir: /mnt/2TB_WD/rishi/aurn/vis_dicts
      image_dir:  visualize_aurn_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 15
      "PM10 (µg/m³)":  45
      "NO2 (µg/m³)":   25
      "SO2 (µg/m³)":   40
      "CO (mg/m³)":    4
      "Ozone (µg/m³)": 100

  imputation:
    dicts_dir: /mnt/2TB_WD/rishi/aurn/vis_dicts
    input_dir: /mnt/2TB_WD/rishi/aurn/aurn_processed
    output_dir: /mnt/2TB_WD/rishi/aurn/imputed
    max_gap_hours: 336
    max_data_missing: 30
    max_workers: 24
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"


cnemc:
  preprocess:
    zip: false
    zip_path:   /mnt/2TB_WD/rishi/cnemc_data.zip
    unzip_dir:  /mnt/2TB_WD/rishi/cnemc_data
    data_dir:   /mnt/2TB_WD/rishi/cnemc_data/cnemc_data
    output_dir: /mnt/2TB_WD/rishi/cnemc_data/by_site_pollutant
    start_date: "2022-07-01 00:00:00"
    end_date:   "2025-06-30 23:00:00"

  visualise:
    make_dicts: true
    folder: /mnt/2TB_WD/rishi/cnemc_data/by_site_pollutant
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    output:
      dicts_dir: /mnt/2TB_WD/rishi/cnemc_data/vis_dicts
      image_dir:  visualize_cnemc_images
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"
    pollutant_limits:
      "PM2.5 (µg/m³)": 15
      "PM10 (µg/m³)":  45
      "NO2 (µg/m³)":   25
      "SO2 (µg/m³)":   40
      "CO (mg/m³)":    4
      "Ozone (µg/m³)": 100

  imputation:
    dicts_dir: /mnt/2TB_WD/rishi/cnemc_data/vis_dicts
    input_dir: /mnt/2TB_WD/rishi/cnemc_data/by_site_pollutant
    output_dir: /mnt/2TB_WD/rishi/cnemc_data/imputed
    max_gap_hours: 336
    max_data_missing: 30
    max_workers: 24
    date_range:
      start: "2022-07-01 00:00:00"
      end:   "2025-06-30 23:00:00"
    features:
      - "PM2.5 (µg/m³)"
      - "PM10 (µg/m³)"
      - "NO2 (µg/m³)"
      - "SO2 (µg/m³)"
      - "CO (mg/m³)"
      - "Ozone (µg/m³)"